server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "g34ksPeEIg4sjPQN1tjahdHggcxX5IVytU0X/f/BUbe8plgGq5YR/HWGA303Wg0h"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
