server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    # Các biến DBMS_CONNECTION, DBMS_PASSWORD, DBMS_USERNAME được khai ở IdentityServiceApplication -> Environment Variables
    # Spring Boot sẽ sử dụng giá trị mặc định nếu biến môi trường không được thiết lập
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service} # thay localhost = mysql-8.0.36 (sql docker) dùng khi deploy lên docker
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "g34ksPeEIg4sjPQN1tjahdHggcxX5IVytU0X/f/BUbe8plgGq5YR/HWGA303Wg0h"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds