# application-product: là config cho product
# muốn sử dụng application.yaml nào thì khai ở IdentityServiceApplication: -Dspring.profiles.active=prod
jwt:
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
